ludos:
  appUrl: 'http://localhost:8080'
  opintopolkuHostname: 'virkailija.untuvaopintopolku.fi'
  instruction-bucket-name: ludos-application-instruction-bucket-untuva
  certificate-bucket-name: ludos-application-certificate-bucket-untuva
  image-bucket-name: ludos-application-image-bucket-untuva
  local-dev-aws-profile: oph-ludos-dev

features:
  additionalSvContentForKertominen: true

server:
  servlet:
    session:
      cookie:
        secure: false
#logging:
# level:
#   org:
#     springframework:
#       jdbc:
#         core: TRACE
#       security: DEBUG
