ludos:
  appUrl: "https://ludos.untuvaopintopolku.fi"
  opintopolkuHostname: "virkailija.untuvaopintopolku.fi"
  instruction-bucket-name: ludos-application-instruction-bucket-untuva
  certificate-bucket-name: ludos-application-certificate-bucket-untuva

server:
  tomcat:
      pattern: "%{X-Forwarded-For}i %l %u %t \"%r\" %s %b"
